export type ValidationAction =
  | "search"
  | "on_search"
  | "select"
  | "on_select"
  | "init"
  | "on_init"
  | "confirm"
  | "on_confirm"
  | "cancel"
  | "on_cancel"
  | "update"
  | "on_update"
  | "status"
  | "on_status"
  | "track"
  | "on_track";
